# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate QIF Neurons
#'
#' @param params Named vector of parameters (delta, etabar, J) to pass to the FREs.
#' @param init_state Named vector of the initial state (r, v) for the ODE system.
#' @param times Time sequence for which output is wanted; the first value of times must be the initial time.
#' @param input Input current or stimulus function of the system.
#' @param neurons Size of the neuronal ensemble.
#' @param sel_neurons Amount of neurons to save on raster data.
#' @export
simulate_qif <- function(params, init_state, times, input, neurons = 10000L, sel_neurons = 300L) {
    .Call('_neuronsim_simulate_qif', PACKAGE = 'neuronsim', params, init_state, times, input, neurons, sel_neurons)
}

